### ISSUE TITLE
Support dynamic data?

### ISSUE THREAD

**Issue by muanis** [box/leche#10]
I have a scenario where I want to run a set of tests against some servers, it's something like this:

The following example works: 

```javascript
describe('general endpoints', function() {
		describe('general endpoints', function() {
			withData([
			        ['http://server1.amazonaws.com'],
			        ['http://server2.amazonaws.com']
			    ], function(basePath) {	
				it('retrieve software version', function(done) {
					request.get(basePath + "/version")
					.end(function(err,res) {
						res.body.should.have.property('version').equal('1.0.0');
						done();
					});
				});
			});
		});

});
```
But the list of servers is dynamic, I can't hard code them. Any idea how can I change leche to accept a function on the dataset parameter so it evaluates the function and use the results?

**Comment by FredKSchott** [comment]
Is there a reason you couldn't build and use that array dynamically? Something like:


```javascript
describe('general endpoints', function() {
	before(function() {
		dynamicServerList = /* Set up servers & create list of URLs */
		lecheServerData   = /* Convert dynamicServerList to form [ [A], [B] ] */
	});
	withData(dynamicLecheData, function(basePath) {	
		// ...
```

**Comment by muanis** [comment]
I tried, but 'withData', is not part of mocha, so it doesn't wait until 'before' is finished. (I guess that's the real reason I always get an empty 'dynamicLecheData').

**Comment by FredKSchott** [comment]
Ah, duh :) Yea you're right, we end up processing the given data before `before()` has gotten a chance to run. The problem is that a function or anything else would also be evaluated before `before()`, since withData is called immediately while the `before()` callback is called when needed for testing.

Could you move the creation of `dynamicLecheData` up a level, to a parent test suite? This way, I \*think\* `withData` would be called after the parent's `before()` callback. Something like:

```javascript
describe('tests', function() {
    before(function() {
        dynamicServerList = /* Set up servers & create list of URLs */
        lecheServerData   = /* Convert dynamicServerList to form [ [A], [B] ] */
    });
    describe('general endpoints', function() {
        withData(dynamicLecheData, function(basePath) { 
            // ...
```

**Comment by nzakas** [comment]
@FredKSchott is correct here. The best thing to do is to populate the data dynamically before passing it to Leche.

**Comment by jeremie-stratumn** [comment]
I have the same problem and the above solution does not solve it for me. here is what I am doing:
```javascript
const withDataFunc = () => {
  console.log('in withData');
  return {'first data': [1]};
};

describe('ABC123', () => {
  console.log('in describe ABC123');
  before(() => {console.log('in before');});
  describe('XYZ456', () => {
    withData(withDataFunc(), arg => {
      it('first it', () => {
        console.log('in first it');
        arg.should.be.exactly(arg);
      });
    });
  });
});
```

Here is the output:
```
in describe ABC123
in withData


  ABC123
in before
    XYZ456
      with first data
in first it
        ✓ first it


  1 passing (193ms)
```

as you can see the `withDataFunc` function is evaluated before the `before` function. I would expect:
Here is the output:
```
in describe ABC123


  ABC123
in before
    XYZ456
in withData
      with first data
in first it
        ✓ first it


  1 passing (193ms)
```

Am I missing something?
