### ISSUE TITLE
support mocha@3

### ISSUE THREAD

**Issue by chrisguttandin** [box/leche#16]
Currently leche requires mocha at version `>=1.18 <3` as a peerDependency. I already used it with mocha@3 and I didn't notice any problems.

Can you please allow leche to be used with a recent version of mocha. Maybe it's just a matter of updating the `peerDependencies` property of the `package.json` file.

**Comment by mattwiller** [comment]
Hey @chrisguttandin, it does look like we might just be able to update the `package.json`.  I'm going to do some more testing on some of our internal codebases to make sure that's the case.

**Comment by chrisguttandin** [comment]
Thank you very much, @mattwiller. Can you maybe also publish the changes to npm?

**Comment by mattwiller** [comment]
Sorry for the delay, the script for cutting a new version wasn't working correctly.  leche@2.1.2 is published now and should work with mocha 3.x

**Comment by chrisguttandin** [comment]
Sorry for being impatient and many thanks again.
