### ISSUE TITLE
lib/leche.js fails with latest version of eslint (0.11.0)

### ISSUE THREAD

**Issue by peterkc** [box/leche#3]
lib/leche.js
  166:17  error  Don't make functions within a loop           no-loop-func
  166:26  error  key is already declared in the upper scope   no-shadow
  167:12  error  Don't make functions within a loop           no-loop-func
  220:30  error  Don't make functions within a loop           no-loop-func
  220:39  error  name is already declared in the upper scope  no-shadow
  221:12  error  Don't make functions within a loop           no-loop-func

**Comment by nzakas** [comment]
Thanks for the report, definitely hadn't gotten around to checking with the latest.
